- name: install elixir
  hosts: default
  sudo: True
  tasks:
    - name: install git
      apt: name=git update_cache=yes
    - name: Check if my_package is installed
      command: dpkg-query -W elixir
      register: my_package_check_deb
      failed_when: my_package_check_deb.rc > 1
      changed_when: my_package_check_deb.rc == 1
    - name: pull down erlang solutions deb package
      get_url: url=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb 
               dest=/tmp/erlang-solutions_1.0_all.deb
               mode=0666
      when: my_package_check_deb.rc == 1
    - name: Install my_package
      apt: deb="/tmp/erlang-solutions_1.0_all.deb"
      sudo: true
      when: my_package_check_deb.rc == 1
    - name: install elixir
      apt: name=elixir update_cache=yes
